"""empty message

Revision ID: 05f338a0fa02
Revises: df3d250b261a
Create Date: 2023-06-29 09:52:08.133633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05f338a0fa02'
down_revision = 'df3d250b261a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
